# Generated by Django 5.2 on 2025-04-20 04:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task_Assigned',
            new_name='TaskAssigned',
        ),
        migrations.RenameModel(
            old_name='Task_Submitted',
            new_name='TaskSubmitted',
        ),
    ]
