# Generated by Django 5.2 on 2025-04-20 18:44

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('requires_approval', models.BooleanField(default=True)),
                ('is_paid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiftStartTime', models.TimeField(choices=[(datetime.time(6, 0), '06:00 AM'), (datetime.time(8, 0), '08:00 AM'), (datetime.time(9, 0), '09:00 AM'), (datetime.time(10, 0), '10:00 AM'), (datetime.time(14, 0), '02:00 PM'), (datetime.time(18, 0), '06:00 PM'), (datetime.time(19, 0), '07:00 PM'), (datetime.time(22, 0), '10:00 PM')])),
                ('shiftEndTime', models.TimeField(choices=[(datetime.time(6, 0), '06:00 AM'), (datetime.time(8, 0), '08:00 AM'), (datetime.time(9, 0), '09:00 AM'), (datetime.time(10, 0), '10:00 AM'), (datetime.time(14, 0), '02:00 PM'), (datetime.time(18, 0), '06:00 PM'), (datetime.time(19, 0), '07:00 PM'), (datetime.time(22, 0), '10:00 PM')])),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='department.department')),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('date', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='department.department')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.DateField(auto_now_add=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_quota', models.PositiveIntegerField()),
                ('carry_forward', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_policies', to='department.department')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='attendance.leavetype')),
            ],
            options={
                'unique_together': {('leave_type', 'department')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('startTime', models.TimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('endTime', models.TimeField(blank=True, null=True)),
                ('Remark', models.CharField(choices=[('Late', 'Late'), ('Over Time', 'Over Time'), ('On Time', 'On Time')], default='On Time', max_length=20)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave'), ('Half day', 'Half day'), ('Holiday', 'Holiday'), ('Week-off', 'Week-off')], default='Present', max_length=20)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_logs', to=settings.AUTH_USER_MODEL)),
                ('attendance_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.attendancedetails')),
            ],
            options={
                'unique_together': {('emp', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserLeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('total_allocated', models.PositiveIntegerField(default=0)),
                ('used', models.PositiveIntegerField(default=0)),
                ('carried_forward', models.PositiveIntegerField(default=0)),
                ('remaining', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_balances', to='attendance.leavepolicy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'leave_policy', 'year')},
            },
        ),
    ]
